name: Deploy React App to FTP

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Check formatting with Prettier
        run: npx prettier --check .

      - name: Build React App
        run: npm run build

      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.SFTP_HOST_HETZNER }}
          username: ${{ secrets.SFTP_USERNAME_HETZNER }}
          password: ${{ secrets.SFTP_PASSWORD_HETZNER }}
          localDir: './dist'
          remoteDir: '/public_html'
